{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alviss-url-shortener.serviceAccountName" . }}
  labels:
{{ include "alviss-url-shortener.labels" . | nindent 4 }}
{{- end -}}
